<?php

namespace common\models;

use Yii;
use yii\behaviors\SluggableBehavior;

/**
 * This is the model class for table "blog_post".
 *
 * @property int $id
 * @property string $title
 * @property string $slug
 * @property string $subtitle
 * @property string $message
 * @property string|null $meta
 * @property string $image
 * @property int $view_count
 * @property int $status
 * @property int $category_id
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property string $created_at
 * @property string|null $updated_at
 */
class BlogPost extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true,
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'blog_post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'slug', 'subtitle', 'message','category_id'], 'required'],
            ['image','required','on' => 'create-post'],
            [['slug', 'subtitle', 'message', 'meta'], 'string'],
            [['view_count', 'status', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['title', 'image'], 'string', 'max' => 200],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'slug' => 'Slug',
            'subtitle' => 'Subtitle',
            'message' => 'Message',
            'meta' => 'Meta',
            'image' => 'Image',
            'view_count' => 'View Count',
            'status' => 'Status',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(),['id'=>'category_id']);
    }

    public function getCreator()
    {
        return $this->hasOne(Admin::className(),['id'=>'created_by']);
    }

    public function getUpdater()
    {
        return $this->hasOne(Admin::className(),['id'=>'updated_by']);
    }

    private function beforeSaveTable()
    {
        if ($this->isNewRecord) {
            $this->created_at = date('y-m-d H-i-s');
            $this->created_by = Yii::$app->user->id;
        } else {
            $this->updated_at = date('y-m-d H-i-s');
            $this->updated_by = Yii::$app->user->id;
        }
    }

    public function beforeValidate()
    {
        $this->beforeSaveTable();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->beforeSaveTable();
        return parent::beforeSave($insert);
    }
}
