<?php

namespace common\models;

use Yii;
use yii\behaviors\SluggableBehavior;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string $slug
 * @property string $title
 * @property string $description
 * @property string|null $meta
 * @property string|null $image
 * @property int|null $position
 * @property int $status
 * @property int $created_by
 * @property int|null $updated_by
 * @property string $created_at
 * @property string|null $updated_at
 */
class Category extends \yii\db\ActiveRecord
{

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title',
                'ensureUnique' => true,
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['slug', 'title', 'description', 'created_by'], 'required'],
            [['description', 'meta', 'type'], 'string'],
            [['position', 'status', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['slug', 'title', 'image'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'slug' => 'Slug',
            'title' => 'Title',
            'description' => 'Description',
            'meta' => 'Meta',
            'image' => 'Image',
            'position' => 'Position',
            'type' => 'Type',
            'status' => 'Status',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getCreator()
    {
        return $this->hasOne(Admin::className(),['id'=>'created_by']);
    }

    public function getUpdater()
    {
        return $this->hasOne(Admin::className(),['id'=>'updated_by']);
    }

    private function beforeSaveTable()
    {
        if ($this->isNewRecord) {
            $this->created_at = date('y-m-d H-i-s');
            $this->created_by = Yii::$app->user->id;
        } else {
            $this->updated_at = date('y-m-d H-i-s');
            $this->updated_by = Yii::$app->user->id;
        }
    }

    public function beforeValidate()
    {
        $this->beforeSaveTable();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->beforeSaveTable();
        return parent::beforeSave($insert);
    }
}
