<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string|null $remember_token
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property int $is_admin
 * @property float $wallet_balance
 * @property int $verification_status
 * @property string|null $name
 * @property string|null $email
 * @property string|null $email_verified_at
 * @property string|null $phone_number
 * @property string|null $password
 * @property string|null $twitter_id
 * @property string|null $username
 * @property string|null $image_path
 * @property string $auth_key
 * @property string|null $phone
 * @property int|null $is_boarded
 * @property int|null $status
 * @property int|null $affiliate_id
 * @property string|null $token
 * @property string|null $state
 * @property string|null $country
 * @property string|null $about
 */
class UserModel extends User
{

    ///This artificial fields are used for change password
    public $current_password;
    public $new_password;
    public $password_repeat;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at', 'email_verified_at'], 'safe'],
            [['is_admin', 'verification_status', 'status'], 'integer'],
            [['wallet_balance'], 'number'],
            [['auth_key'], 'required'],
            [['token'], 'string'],
            [['remember_token'], 'string', 'max' => 100],
            [['name', 'email', 'phone_number', 'password', 'twitter_id', 'username', 'image_path'], 'string', 'max' => 191],
            [['auth_key'], 'string', 'max' => 32],
            [['phone'], 'string', 'max' => 15],

            // For changing of password
            [['current_password', 'new_password', 'password_repeat'], 'string', 'on' => 'password'],
            [['new_password', 'password_repeat'], 'required', 'on' => 'password'],
            ['password_repeat', 'compare', 'compareAttribute' => 'new_password', 'on' => 'password'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'remember_token' => 'Remember Token',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'is_admin' => 'Is Admin',
            'wallet_balance' => 'Wallet Balance',
            'verification_status' => 'Verification Status',
            'name' => 'Name',
            'email' => 'Email',
            'email_verified_at' => 'Email Verified At',
            'phone_number' => 'Phone Number',
            'password' => 'Password',
            'twitter_id' => 'Twitter ID',
            'username' => 'Username',
            'image_path' => 'Image Path',
            'auth_key' => 'Auth Key',
            'phone' => 'Phone',
            'status' => 'Status',
            'token' => 'Token',
        ];
    }

    public function beforeValidate()
    {
        if (empty($this->auth_key)) {
            $this->auth_key = Yii::$app->security->generateRandomString();
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_at = date('Y-m-d H:i:s');
        } else {
            $this->updated_at = date('Y-m-d H:i:s');
        }
        return parent::beforeSave($insert);
    }
}